version: '3.8'

services:
  frontend-nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      # Прокидываем конфиг (заменяем дефолтный конфиг nginx)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Прокидываем собранные папки
      - ./web/dist:/app/web/dist
      - ./admin_panel/dist:/app/admin_panel/dist