server {
    listen 3000;
    server_name localhost;

    include /etc/nginx/mime.types;

    location / {
        root   /app/web/dist;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /admin {
        alias /app/admin_panel/dist;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }
}